-- MN Aesthetic Supabase database

-- Run this entire file in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  subtitle text not null,
  description text not null,
  price text not null,
  tag text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.appointments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  service_id bigint not null references public.services(id),
  date date not null,
  time time not null,
  notes text default '',
  status text not null default 'confirmed'
    check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  created_at timestamptz not null default now()
);

create index if not exists appointments_user_id_idx
  on public.appointments(user_id);

create index if not exists appointments_date_time_idx
  on public.appointments(date, time);

insert into public.services (id, title, subtitle, description, price, tag)
values
  (1, 'Diode Laser', 'Hair Removal',
   'Smooth, comfortable diode laser treatment with a personalized approach.',
   'From 40 GEL', 'POPULAR'),

  (2, 'Nails &', 'Pedicure',
   'Elegant nail care and pedicure services designed for a clean, polished finish.',
   'From 35 GEL', 'BEAUTY')

on conflict (id) do update set
  title = excluded.title,
  subtitle = excluded.subtitle,
  description = excluded.description,
  price = excluded.price,
  tag = excluded.tag;

select setval(
  pg_get_serial_sequence('public.services', 'id'),
  greatest((select max(id) from public.services), 1),
  true
);

alter table public.services enable row level security;

alter table public.appointments enable row level security;

drop policy if exists "Anyone can view services" on public.services;

create policy "Anyone can view services"
on public.services for select
to anon, authenticated
using (true);

drop policy if exists "Users can view their own appointments" on public.appointments;

create policy "Users can view their own appointments"
on public.appointments for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create their own appointments" on public.appointments;

create policy "Users can create their own appointments"
on public.appointments for insert
to authenticated
with check (auth.uid() = user_id);

-- Customers can cancel their own appointment, but cannot change its owner.

drop policy if exists "Users can cancel their own appointments" on public.appointments;

create policy "Users can cancel their own appointments"
on public.appointments for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Prevent two active bookings from occupying the exact same date and time.

create unique index if not exists appointments_active_slot_unique
on public.appointments(date, time)
where status in ('pending', 'confirmed');

-- Optional helper view for your admin dashboard later.

create or replace view public.appointment_details as
select
  a.id,
  a.user_id,
  a.service_id,
  s.title,
  s.subtitle,
  s.price,
  a.date,
  a.time,
  a.notes,
  a.status,
  a.created_at
from public.appointments a
join public.services s on s.id = a.service_id;

-- Make existing pending appointments confirmed too.

update public.appointments
set status = 'confirmed'
where status = 'pending';